### ISSUE TITLE
albums are not supported?

### ISSUE THREAD

**Issue by TheNomad11** [fm16191/spotify-recorder#13]
Recording tracks works well, but albums do not seem to be supported?

**Comment by fm16191** [comment]
Hi, and sorry for the late reply

Just wanted to let you know that albums are now supported!
Thanks for sharing the issue/feature request, it wasn't hard to implement actually.
Cheers,

**Comment by TheNomad11** [comment]
oh wow, thanks so much!!!! I was looking so hard for a solution that works with the newest Linux Mint!!
