### ISSUE TITLE
Dependency on mutagen is not declared or logic bug wrt. metadata

### ISSUE THREAD

**Issue by kedorlaomer** [fm16191/spotify-recorder#3]
Thank you so much for this wonderful project! I just installed it in a fresh VM (Ubuntu 22.04) and found that `python3 api.py <someSpotifyUrl>` complained it cannot find `mutagen`. This can be solved easily by either

* `pip3 install mutagen` or
* `apt install -y python3-mutagen` (in Ubuntu)

In both cases, running `python3 api.py <somePlaylist>` yields an error related to a call in `mutagen`. The relevant line is https://github.com/fm16191/spotify-recorder/blob/42d24d941c0d0bc83f67637cbd1d4787bd154f3a/api.py#L123 where `filepath` is either a string or a boolean (see https://github.com/fm16191/spotify-recorder/blob/42d24d941c0d0bc83f67637cbd1d4787bd154f3a/api.py#L106) . If it's a boolean, then `mutagen` will be asked to edit a file `False` which obviously yields an error.

Do you think that the error I'm observing is related to an incompatible version of `mutagen` or is it a real logic bug (independent of `mutagen`)?

**Comment by fm16191** [comment]
Hi !
Song's filepath was not updated after the song being recorded, hence mutagen raising an error ... thanks for reporting the issue! This has been fixed.
