### ISSUE TITLE
Playlist download not working; tries editing non-existing file

### ISSUE THREAD

**Issue by kedorlaomer** [fm16191/spotify-recorder#4]
For me, the fix for bug #3 did not quite work. When starting with a fresh checkout (i. e., no `songs`, `songs_build`, `playlist.json`), the execution of `python3 api.py <some playlist>` yields a similar error at https://github.com/fm16191/spotify-recorder/blob/72ca34cfe796abd0c1b253abe1a6134a29caf850/api.py#L236 namely that `filepath` is the path to a non-existing file. Apparently, https://github.com/fm16191/spotify-recorder/blob/72ca34cfe796abd0c1b253abe1a6134a29caf850/api.py#L123 is called on a non-existing file name `filepath` which causes `mutagen` to fail. Can you reproduce this?

**Comment by fm16191** [comment]
Hi !
You absolutely right, that was an oversight ...

**Comment by fm16191** [comment]
I did closed it a bit early, please let me know if it now works for you !
