### ISSUE TITLE
Only first 100 items of playlists get downloaded

### ISSUE THREAD

**Issue by kedorlaomer** [fm16191/spotify-recorder#6]
The reason is https://github.com/fm16191/spotify-recorder/blob/9527c15eddfa948af12735bc71382fe1e42e1fb2/api.py#L150 The function `playlist` returns only the first 100 items of the playlist and does not allow to ask for more. Instead, the function [`playlist_items`](https://spotipy.readthedocs.io/en/2.22.1/?highlight=playlist_items#spotipy.client.Spotify.playlist_items) can be used. Its interface allows to add `offset` and `limit` such that large playlists can be downloaded in bunches.

**Comment by guemmelboy123** [comment]
do this:

`def playlist_by_id(self, playlist_id=None, filename=None):
        if not playlist_id:
            return INFO("No playlist specified")
        results = self.sp.playlist(playlist_id)
        tracks = results['tracks']
        while tracks['next']:
            tracks = self.sp.next(tracks)
            results['tracks']['items'].extend(tracks['items'])
        if filename:
            with open(filename, "w") as fw:
                json.dump(results, fw, indent=2)
        return results`
